[book]
authors = ["Chris Pecunies"]
language = "en"
multilingual = false
src = "src"
title = "The dlog book"
description = "The book describing the many different aspects of Dlog, and different possible ways to use it."

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = true

[preprocessor.index]

[processor.mathjax]
renderers = ["html"]

[preprocessor.links]
renderers = ["html"]

[output.html]
theme = "light"
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
copy-fonts = true
additional-css = ["book.css"]
mathjax-support = true
google-analytics = "G-5FW053QJP8"
additional-js = ["book.js"]
git-repository-url = "https://github.com/clpi/dlog"
git-repository-icon = "fa-github"
input-404 = "404.md"
site-url = "https://dlog.div.is/book/"
cname = "dlog.div.is"

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 40
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.html.redirect]
