name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --verbose


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose

  release:

    runs-on: ubuntu-latest

    if: "contains(github.event.head_commit.message, '[release]')"
    steps:
    - name: Build deb
      run: |
        cargo install cargo-deb
        cargo deb
        strip ./target/release/dlog
        mkdir -p ./release
        mv target/debian/*.deb ./release/dlog.deb
        tar -C ./target/release -czvf ./release/dlog.deb

